name: GitActions-Demo3
on:
  schedule:
    - cron: '49 12 * * *'
jobs:
  check-time:
    runs-on: ubuntu-latest
    steps:
      - name: Report current time
        run:
          echo "This workflow ran on a schedule!"
          echo "Current UTC time: $(date -U)"
          echo "Current local time (on runner): $(date)"
